// CNC Simulator Pro — International Material Catalog (ISO 513 Classification)
// Covers Steels (P), Stainless Steels (M), Cast Iron (K), Non-Ferrous (N), Superalloys (S), Hardened (H) & Synthetics (O)

export type IsoMaterialGroup = "P (Steel)" | "M (Stainless)" | "K (Cast Iron)" | "N (Non-Ferrous)" | "S (Superalloys)" | "H (Hardened)" | "O (Synthetics)";

export interface CncMaterial {
  id: string;
  name: string;
  isoGroup: IsoMaterialGroup;
  color: string; // workpiece top surface color in 3D
  sideColor: string; // workpiece side/bottom color in 3D
  roughness: number; // PBR surface roughness (0..1)
  metalness: number; // PBR metalness (0..1)
  density: number; // g/cm³
  // cutting parameters (for baseline carbide tooling)
  surfaceSpeed: number; // Vc m/min
  chipLoad: number; // fz mm/tooth
  maxDepthOfCut: number; // axial Ae mm
  maxStepover: number; // radial % of diameter
  coolant: "flood" | "mist" | "air" | "none";
  notes: string;
}

export const MATERIAL_LIBRARY: CncMaterial[] = [
  // --- ISO N: NON-FERROUS METALS ---
  {
    id: "aluminum-6061",
    name: "Aluminum 6061-T6 (ISO N01)",
    isoGroup: "N (Non-Ferrous)",
    color: "#d1d5db",
    sideColor: "#9ca3af",
    roughness: 0.35,
    metalness: 0.85,
    density: 2.7,
    surfaceSpeed: 250,
    chipLoad: 0.05,
    maxDepthOfCut: 6,
    maxStepover: 50,
    coolant: "flood",
    notes: "General structural aluminum. Excellent machinability, use sharp polished carbide and flood coolant.",
  },
  {
    id: "aluminum-7075",
    name: "Aluminum 7075-T6 (ISO N02)",
    isoGroup: "N (Non-Ferrous)",
    color: "#cbd5e1",
    sideColor: "#94a3b8",
    roughness: 0.3,
    metalness: 0.9,
    density: 2.81,
    surfaceSpeed: 220,
    chipLoad: 0.045,
    maxDepthOfCut: 5,
    maxStepover: 45,
    coolant: "flood",
    notes: "Aerospace high-strength zinc-aluminum alloy. Harder chip formation, crisp milled surface finish.",
  },
  {
    id: "aluminum-2024",
    name: "Aluminum 2024-T3 (ISO N03)",
    isoGroup: "N (Non-Ferrous)",
    color: "#e2e8f0",
    sideColor: "#cbd5e1",
    roughness: 0.32,
    metalness: 0.88,
    density: 2.78,
    surfaceSpeed: 210,
    chipLoad: 0.04,
    maxDepthOfCut: 5,
    maxStepover: 45,
    coolant: "flood",
    notes: "Copper-aluminum aircraft alloy. High fatigue resistance, good surface finish.",
  },
  {
    id: "brass",
    name: "Brass C360 (ISO N10)",
    isoGroup: "N (Non-Ferrous)",
    color: "#fbbf24",
    sideColor: "#d97706",
    roughness: 0.25,
    metalness: 0.92,
    density: 8.5,
    surfaceSpeed: 300,
    chipLoad: 0.06,
    maxDepthOfCut: 6,
    maxStepover: 50,
    coolant: "air",
    notes: "Free-machining brass. Short powdery chips, mirror surface finish, air blast.",
  },
  {
    id: "copper",
    name: "Copper C110 Pure (ISO N11)",
    isoGroup: "N (Non-Ferrous)",
    color: "#f97316",
    sideColor: "#c2410c",
    roughness: 0.28,
    metalness: 0.94,
    density: 8.96,
    surfaceSpeed: 150,
    chipLoad: 0.04,
    maxDepthOfCut: 4,
    maxStepover: 35,
    coolant: "flood",
    notes: "Electrolytic tough pitch copper. Highly ductile, requires razor-sharp tools.",
  },

  // --- ISO P: STEELS ---
  {
    id: "steel-mild",
    name: "Mild Steel AISI 1018 (ISO P01)",
    isoGroup: "P (Steel)",
    color: "#94a3b8",
    sideColor: "#64748b",
    roughness: 0.45,
    metalness: 0.75,
    density: 7.87,
    surfaceSpeed: 90,
    chipLoad: 0.04,
    maxDepthOfCut: 3,
    maxStepover: 30,
    coolant: "flood",
    notes: "Low carbon structural steel. Tough and ductile, requires rigid setup & moderate feeds.",
  },
  {
    id: "steel-alloy-4140",
    name: "Alloy Steel AISI 4140 (ISO P02)",
    isoGroup: "P (Steel)",
    color: "#64748b",
    sideColor: "#475569",
    roughness: 0.4,
    metalness: 0.8,
    density: 7.85,
    surfaceSpeed: 80,
    chipLoad: 0.035,
    maxDepthOfCut: 2.5,
    maxStepover: 30,
    coolant: "flood",
    notes: "Chromium-molybdenum high-tensile steel. Excellent fatigue strength.",
  },

  // --- ISO M: STAINLESS STEELS ---
  {
    id: "steel-stainless",
    name: "Stainless Steel 304 (ISO M01)",
    isoGroup: "M (Stainless)",
    color: "#cbd5e1",
    sideColor: "#64748b",
    roughness: 0.35,
    metalness: 0.85,
    density: 8.0,
    surfaceSpeed: 70,
    chipLoad: 0.03,
    maxDepthOfCut: 2,
    maxStepover: 25,
    coolant: "flood",
    notes: "Austenitic 18/8 stainless. Rapid work-hardening, positive rake angle mandatory.",
  },
  {
    id: "steel-stainless-316l",
    name: "Stainless Steel 316L (ISO M02)",
    isoGroup: "M (Stainless)",
    color: "#94a3b8",
    sideColor: "#475569",
    roughness: 0.32,
    metalness: 0.88,
    density: 8.0,
    surfaceSpeed: 65,
    chipLoad: 0.028,
    maxDepthOfCut: 2,
    maxStepover: 25,
    coolant: "flood",
    notes: "Marine & surgical grade molybdenum stainless. Gummy chip formation.",
  },

  // --- ISO S: SUPERALLOYS & TITANIUM ---
  {
    id: "titanium-grade5",
    name: "Titanium Ti-6Al-4V (ISO S01)",
    isoGroup: "S (Superalloys)",
    color: "#64748b",
    sideColor: "#334155",
    roughness: 0.3,
    metalness: 0.85,
    density: 4.43,
    surfaceSpeed: 50,
    chipLoad: 0.03,
    maxDepthOfCut: 2,
    maxStepover: 20,
    coolant: "flood",
    notes: "Grade 5 Aerospace Titanium. Low thermal conductivity, high heat concentration at tool tip.",
  },

  // --- ISO K: CAST IRON ---
  {
    id: "cast-iron-gray",
    name: "Gray Cast Iron Class 40 (ISO K01)",
    isoGroup: "K (Cast Iron)",
    color: "#475569",
    sideColor: "#1e293b",
    roughness: 0.6,
    metalness: 0.65,
    density: 7.2,
    surfaceSpeed: 110,
    chipLoad: 0.05,
    maxDepthOfCut: 3.5,
    maxStepover: 40,
    coolant: "air",
    notes: "High graphite damping. Crumbly powdery chips, air blast or dry machining.",
  },

  // --- ISO O: SYNTHETICS & COMPOSITES ---
  {
    id: "delrin",
    name: "Delrin POM-H Acetal (ISO O01)",
    isoGroup: "O (Synthetics)",
    color: "#f8fafc",
    sideColor: "#e2e8f0",
    roughness: 0.2,
    metalness: 0.05,
    density: 1.42,
    surfaceSpeed: 200,
    chipLoad: 0.08,
    maxDepthOfCut: 8,
    maxStepover: 60,
    coolant: "air",
    notes: "Homopolymer acetal engineering plastic. High feed rates, razor sharp flutes.",
  },
  {
    id: "peek",
    name: "PEEK Industrial (ISO O02)",
    isoGroup: "O (Synthetics)",
    color: "#e2e8f0",
    sideColor: "#cbd5e1",
    roughness: 0.25,
    metalness: 0.1,
    density: 1.32,
    surfaceSpeed: 180,
    chipLoad: 0.06,
    maxDepthOfCut: 6,
    maxStepover: 50,
    coolant: "flood",
    notes: "High-performance thermoplastic. High temperature resistance, stress-relieved stock.",
  },
  {
    id: "acrylic",
    name: "Acrylic PMMA Optical (ISO O03)",
    isoGroup: "O (Synthetics)",
    color: "#f1f5f9",
    sideColor: "#cbd5e1",
    roughness: 0.1,
    metalness: 0.0,
    density: 1.19,
    surfaceSpeed: 250,
    chipLoad: 0.07,
    maxDepthOfCut: 5,
    maxStepover: 50,
    coolant: "air",
    notes: "Transparent optical acrylic. Single-flute O-flute cutters prevent chip re-welding.",
  },
  {
    id: "carbon-fiber",
    name: "Carbon Fiber Composite (ISO O10)",
    isoGroup: "O (Synthetics)",
    color: "#1e293b",
    sideColor: "#0f172a",
    roughness: 0.4,
    metalness: 0.2,
    density: 1.55,
    surfaceSpeed: 300,
    chipLoad: 0.04,
    maxDepthOfCut: 3,
    maxStepover: 35,
    coolant: "air",
    notes: "Abrasive CF matrix. Requires PCD diamond or burr-style compression cutters.",
  },
  {
    id: "fr4-g10",
    name: "FR4 / G10 Epoxy Glass (ISO O11)",
    isoGroup: "O (Synthetics)",
    color: "#a3e635",
    sideColor: "#65a30d",
    roughness: 0.45,
    metalness: 0.1,
    density: 1.85,
    surfaceSpeed: 280,
    chipLoad: 0.04,
    maxDepthOfCut: 4,
    maxStepover: 40,
    coolant: "air",
    notes: "Woven glass epoxy composite. High dust extraction, carbide router bits.",
  },
];

export function getMaterialById(id: string): CncMaterial {
  return MATERIAL_LIBRARY.find((m) => m.id === id) ?? MATERIAL_LIBRARY[0];
}
