// CNC Simulator Pro — International Standard Tool Library (ISO 13399 & ANSI)
// Covers 24 precision tools for Milling, Drilling, Reaming, Tapping, Surfacing & Lathe Turning

export type ToolType =
  | "end_mill"
  | "ball_nose"
  | "bull_nose"
  | "roughing_end_mill"
  | "drill"
  | "spot_drill"
  | "reamer"
  | "chamfer"
  | "face_mill"
  | "fly_cutter"
  | "tap"
  | "thread_mill"
  | "lathe_turning"
  | "lathe_finishing"
  | "lathe_threading"
  | "lathe_grooving"
  | "lathe_boring"
  | "carving_tapered";

export type OperationCategory = "Milling" | "Drilling" | "Holemaking" | "Turning" | "Finishing";

export interface CncTool {
  number: number; // T1, T2, T3 ...
  isoCode: string; // ISO 13399 Tool Code designation
  name: string;
  type: ToolType;
  category: OperationCategory;
  diameter: number; // mm (cutting diameter)
  length: number; // mm (cutting flute length)
  flutes: number;
  shankDiameter: number; // mm
  cornerRadius?: number; // mm (for bull nose)
  pointAngle?: number; // degrees (90°, 118°, 140° for drills/chamfers)
  color: string; // hex color for 3D tool model & UI badge
  surfaceSpeed: number; // m/min (Vc baseline)
  chipLoad: number; // mm/tooth (fz baseline)
  description: string;
}

export const TOOL_LIBRARY: CncTool[] = [
  // --- MILLING TOOLS ---
  {
    number: 1,
    isoCode: "ISO 1641 - APMT1135",
    name: "End Mill Ø6 (3-Flute Carbide)",
    type: "end_mill",
    category: "Milling",
    diameter: 6,
    length: 20,
    flutes: 3,
    shankDiameter: 6,
    color: "#e8c878",
    surfaceSpeed: 250,
    chipLoad: 0.05,
    description: "DIN 844 ISO 1641 standard 3-flute solid carbide end mill. General pocketing & profiling.",
  },
  {
    number: 2,
    isoCode: "ISO 1641 - APMT1604",
    name: "End Mill Ø10 (4-Flute Rougher)",
    type: "end_mill",
    category: "Milling",
    diameter: 10,
    length: 25,
    flutes: 4,
    shankDiameter: 10,
    color: "#d4a44a",
    surfaceSpeed: 220,
    chipLoad: 0.07,
    description: "4-flute heavy-duty end mill for high material removal rates in aluminum & mild steel.",
  },
  {
    number: 3,
    isoCode: "DIN 338 - HSS-Co5",
    name: "Twist Drill Ø3 (HSS-Cobalt)",
    type: "drill",
    category: "Drilling",
    diameter: 3,
    length: 30,
    flutes: 2,
    shankDiameter: 3,
    pointAngle: 118,
    color: "#c0c6cf",
    surfaceSpeed: 80,
    chipLoad: 0.06,
    description: "DIN 338 HSS-Co5 jobber drill for G81/G83 drilling cycles.",
  },
  {
    number: 4,
    isoCode: "ISO 13399 - BEM6-R3",
    name: "Ball Nose Ø6 (R3 3D Surfacing)",
    type: "ball_nose",
    category: "Finishing",
    diameter: 6,
    length: 18,
    flutes: 2,
    shankDiameter: 6,
    cornerRadius: 3,
    color: "#b8e0a3",
    surfaceSpeed: 200,
    chipLoad: 0.04,
    description: "Ball nose end mill for 3D sculptured surfaces & organic CAD contours.",
  },
  {
    number: 5,
    isoCode: "ISO 90° - CHM10",
    name: "Chamfer Mill Ø10 (90° Edge Break)",
    type: "chamfer",
    category: "Finishing",
    diameter: 10,
    length: 12,
    flutes: 2,
    shankDiameter: 6,
    pointAngle: 90,
    color: "#f4a460",
    surfaceSpeed: 180,
    chipLoad: 0.05,
    description: "90° double-ended chamfer cutter for edge deburring & countersinking.",
  },
  {
    number: 6,
    isoCode: "ISO 22 - FMA50-45°",
    name: "Face Mill Ø50 (45° Shell Mill 5-Insert)",
    type: "face_mill",
    category: "Milling",
    diameter: 50,
    length: 14,
    flutes: 5,
    shankDiameter: 25,
    color: "#9aa6b2",
    surfaceSpeed: 300,
    chipLoad: 0.12,
    description: "ISO 22 arbor 45° indexable face mill for rapid surface flattening.",
  },
  {
    number: 7,
    isoCode: "DIN 1897 - NC-NC8",
    name: "NC Spot Drill Ø8 (90° Point)",
    type: "spot_drill",
    category: "Drilling",
    diameter: 8,
    length: 14,
    flutes: 2,
    shankDiameter: 8,
    pointAngle: 90,
    color: "#e0a3a3",
    surfaceSpeed: 120,
    chipLoad: 0.05,
    description: "High-rigidity stub NC spot drill for zero-drift hole starting.",
  },
  {
    number: 8,
    isoCode: "DIN 212 - RM5-H7",
    name: "Precision Reamer Ø5 (H7 Tolerance)",
    type: "reamer",
    category: "Holemaking",
    diameter: 5,
    length: 35,
    flutes: 6,
    shankDiameter: 5,
    color: "#a3c4e0",
    surfaceSpeed: 30,
    chipLoad: 0.08,
    description: "DIN 212 H7 precision spiral-flute reamer for IT7 pin holes.",
  },

  // --- EXTENDED INTERNATIONAL TOOLS ---
  {
    number: 9,
    isoCode: "ISO 13399 - MEM2-2F",
    name: "Micro End Mill Ø2 (2-Flute Stub)",
    type: "end_mill",
    category: "Milling",
    diameter: 2,
    length: 8,
    flutes: 2,
    shankDiameter: 4,
    color: "#e2e8f0",
    surfaceSpeed: 220,
    chipLoad: 0.015,
    description: "Precision micro end mill for intricate slots, small ribs & PCB work.",
  },
  {
    number: 10,
    isoCode: "DIN 844-K - ROUGH12",
    name: "Roughing End Mill Ø12 (Corn Cob)",
    type: "roughing_end_mill",
    category: "Milling",
    diameter: 12,
    length: 28,
    flutes: 4,
    shankDiameter: 12,
    color: "#eab308",
    surfaceSpeed: 180,
    chipLoad: 0.09,
    description: "Wave-profile knuckle end mill for heavy metal removal with small chips.",
  },
  {
    number: 11,
    isoCode: "ISO 13399 - BEM3-R1.5",
    name: "Micro Ball Nose Ø3 (R1.5)",
    type: "ball_nose",
    category: "Finishing",
    diameter: 3,
    length: 10,
    flutes: 2,
    shankDiameter: 4,
    cornerRadius: 1.5,
    color: "#86efac",
    surfaceSpeed: 190,
    chipLoad: 0.025,
    description: "Fine 3D finishing ball end mill for small fillets & mold cavities.",
  },
  {
    number: 12,
    isoCode: "ISO 1641 - BN10-R1",
    name: "Bull Nose Ø10 R1 (Corner Radius)",
    type: "bull_nose",
    category: "Milling",
    diameter: 10,
    length: 22,
    flutes: 4,
    shankDiameter: 10,
    cornerRadius: 1.0,
    color: "#f97316",
    surfaceSpeed: 230,
    chipLoad: 0.065,
    description: "Toroid / bull nose end mill with 1mm corner radius for high-feed pocketing.",
  },
  {
    number: 13,
    isoCode: "DIN 338 - D6.8-M8",
    name: "Tap Drill Ø6.8 (For M8 Thread)",
    type: "drill",
    category: "Drilling",
    diameter: 6.8,
    length: 40,
    flutes: 2,
    shankDiameter: 6.8,
    pointAngle: 140,
    color: "#94a3b8",
    surfaceSpeed: 90,
    chipLoad: 0.08,
    description: "Carbide 140° drill specifically sized for pre-tapping M8×1.25 holes.",
  },
  {
    number: 14,
    isoCode: "DIN 338 - D8.5-M10",
    name: "Tap Drill Ø8.5 (For M10 Thread)",
    type: "drill",
    category: "Drilling",
    diameter: 8.5,
    length: 45,
    flutes: 2,
    shankDiameter: 8.5,
    pointAngle: 140,
    color: "#64748b",
    surfaceSpeed: 90,
    chipLoad: 0.09,
    description: "Carbide drill sized for pre-tapping M10×1.5 metric coarse holes.",
  },
  {
    number: 15,
    isoCode: "ISO 529 - TAP-M8",
    name: "Spiral Flute Tap M8×1.25",
    type: "tap",
    category: "Holemaking",
    diameter: 8,
    length: 22,
    flutes: 3,
    shankDiameter: 8,
    color: "#38bdf8",
    surfaceSpeed: 20,
    chipLoad: 1.25,
    description: "ISO metric coarse M8 spiral flute machine tap for blind-hole tapping.",
  },
  {
    number: 16,
    isoCode: "ISO 13399 - TM-M6-M12",
    name: "Carbide Thread Mill M6-M12",
    type: "thread_mill",
    category: "Milling",
    diameter: 6,
    length: 16,
    flutes: 4,
    shankDiameter: 6,
    color: "#c084fc",
    surfaceSpeed: 160,
    chipLoad: 0.03,
    description: "Helical interpolating thread mill for pitch 1.0 to 1.75 metric threads.",
  },
  {
    number: 17,
    isoCode: "ANSI B94.19 - FLY40",
    name: "Single-Insert Fly Cutter Ø40",
    type: "fly_cutter",
    category: "Finishing",
    diameter: 40,
    length: 12,
    flutes: 1,
    shankDiameter: 16,
    color: "#a855f7",
    surfaceSpeed: 350,
    chipLoad: 0.15,
    description: "Single-point fly cutter for ultra-high glass mirror finish on aluminum.",
  },
  {
    number: 18,
    isoCode: "ISO 1832 - CNMG 120408",
    name: "Lathe OD Rougher (CNMG 120408 80°)",
    type: "lathe_turning",
    category: "Turning",
    diameter: 12,
    length: 25,
    flutes: 1,
    shankDiameter: 20,
    cornerRadius: 0.8,
    color: "#38bdf8",
    surfaceSpeed: 260,
    chipLoad: 0.25,
    description: "ISO 80° diamond CNMG 120408 carbide insert for heavy external turning.",
  },
  {
    number: 19,
    isoCode: "ISO 1832 - VNMG 160404",
    name: "Lathe OD Finisher (VNMG 160404 35°)",
    type: "lathe_finishing",
    category: "Turning",
    diameter: 10,
    length: 25,
    flutes: 1,
    shankDiameter: 20,
    cornerRadius: 0.4,
    color: "#4ade80",
    surfaceSpeed: 320,
    chipLoad: 0.12,
    description: "ISO 35° acute diamond VNMG insert for precision profile turning.",
  },
  {
    number: 20,
    isoCode: "ISO 1832 - 16ER 1.5ISO",
    name: "Lathe Threading Tool (16ER 60°)",
    type: "lathe_threading",
    category: "Turning",
    diameter: 8,
    length: 20,
    flutes: 1,
    shankDiameter: 20,
    color: "#f43f5e",
    surfaceSpeed: 140,
    chipLoad: 1.5,
    description: "External metric 60° laydown threading insert for CNC G76 threading.",
  },
  {
    number: 21,
    isoCode: "ISO 1832 - N123 3mm",
    name: "Lathe Parting & Grooving Blade (3mm)",
    type: "lathe_grooving",
    category: "Turning",
    diameter: 3,
    length: 20,
    flutes: 1,
    shankDiameter: 20,
    color: "#fb923c",
    surfaceSpeed: 180,
    chipLoad: 0.08,
    description: "3mm neutral grooving and cut-off blade for parting turned workpieces.",
  },
  {
    number: 22,
    isoCode: "ISO 1832 - S16T-CCMT 09",
    name: "Lathe Internal Boring Bar (CCMT 09T3)",
    type: "lathe_boring",
    category: "Turning",
    diameter: 16,
    length: 120,
    flutes: 1,
    shankDiameter: 16,
    cornerRadius: 0.4,
    color: "#a7f3d0",
    surfaceSpeed: 210,
    chipLoad: 0.15,
    description: "Steel shank S16T boring bar with 80° CCMT insert for internal ID boring.",
  },
  {
    number: 23,
    isoCode: "ISO 13399 - TCB-5DEG",
    name: "Tapered Carving Bit (5° Ball Tip R0.5)",
    type: "carving_tapered",
    category: "Finishing",
    diameter: 6,
    length: 30,
    flutes: 2,
    shankDiameter: 6,
    cornerRadius: 0.5,
    color: "#fef08a",
    surfaceSpeed: 280,
    chipLoad: 0.02,
    description: "5-degree tapered 2-flute ball nose carving bit for deep 3D reliefs.",
  },
  {
    number: 24,
    isoCode: "ISO 13399 - PCD-EM6",
    name: "PCD Diamond End Mill Ø6",
    type: "end_mill",
    category: "Milling",
    diameter: 6,
    length: 15,
    flutes: 2,
    shankDiameter: 6,
    color: "#67e8f9",
    surfaceSpeed: 600,
    chipLoad: 0.06,
    description: "Polycrystalline Diamond (PCD) tipped end mill for carbon fiber & composites.",
  },
];

export function getToolByNumber(n: number): CncTool | undefined {
  return TOOL_LIBRARY.find((t) => t.number === n);
}

export function toolRadius(n: number): number {
  return (getToolByNumber(n)?.diameter ?? 6) / 2;
}

export const TOOL_TYPE_ICON: Record<ToolType, string> = {
  end_mill: "▭",
  ball_nose: "◡",
  bull_nose: "└┘",
  roughing_end_mill: "▤",
  drill: "▲",
  spot_drill: "▼",
  reamer: "▮",
  chamfer: "◣",
  face_mill: "⊞",
  fly_cutter: "✦",
  tap: "≡",
  thread_mill: "⎌",
  lathe_turning: "◢",
  lathe_finishing: "◣",
  lathe_threading: "⋀",
  lathe_grooving: "▍",
  lathe_boring: "⊏",
  carving_tapered: "∇",
};
