# These appear as "Sponsor" buttons on the repo.
# Uncomment/add lines for the platforms you use.

# github: [rudra496]
# patreon: # your username
# ko_fi: # your username
# buy_me_a_coffee: # your username
custom: ["https://rudra496.github.io/site"]
